# Generated by Django 5.2.1 on 2025-06-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_author_alter_post_content_alter_post_title_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
